SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;ef17d2

-- SQRIBE/TABLE;ef17d2
-- Adding 2 rows to dbo.UFUserSecurity

BEGIN TRANSACTION

-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[UFUserSecurity] ([User],[ManageDataSources],[ManagePreValueSources],[ManageWorkflows],[ManageForms]) VALUES (N'-1',1,1,1,1);
-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[UFUserSecurity] ([User],[ManageDataSources],[ManagePreValueSources],[ManageWorkflows],[ManageForms]) VALUES (N'1',0,0,0,1);

COMMIT TRANSACTION

