SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;03d113

-- SQRIBE/TABLE;03d113
-- Adding 3 rows to dbo.UFRecordDataString

SET IDENTITY_INSERT [dbo].[UFRecordDataString] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[UFRecordDataString] ([Id],[Key],[Value]) VALUES (1,'32B78E8A-989B-46A7-93B1-861F9FBA1FA4',N'Michael');
-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[UFRecordDataString] ([Id],[Key],[Value]) VALUES (2,'38950EEB-11C4-44A9-94E2-808301B03A13',N'Argentini');
-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[UFRecordDataString] ([Id],[Key],[Value]) VALUES (3,'BFC919B6-EE20-4CEC-93AE-9E53A756C734',N'magic@fynydd.com');

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[UFRecordDataString] OFF

