SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;03d113

-- SQRIBE/TABLE;03d113
-- Adding 2 rows to dbo.UFUserFormSecurity

SET IDENTITY_INSERT [dbo].[UFUserFormSecurity] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[UFUserFormSecurity] ([Id],[User],[Form],[HasAccess],[AllowInEditor],[SecurityType]) VALUES (1,N'-1','DEB50D01-FF86-4CEE-920B-9F8F9C637CF8',1,1,0);
-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[UFUserFormSecurity] ([Id],[User],[Form],[HasAccess],[AllowInEditor],[SecurityType]) VALUES (2,N'1','DEB50D01-FF86-4CEE-920B-9F8F9C637CF8',1,1,0);

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[UFUserFormSecurity] OFF

