SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;03d113

-- SQRIBE/TABLE;03d113
-- Adding 1 row to dbo.umbracoKeyValue

BEGIN TRANSACTION

-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[umbracoKeyValue] ([key],[value],[updated]) VALUES (N'Umbraco.Core.Upgrader.State+Umbraco.Core',N'{5B1E0D93-F5A3-449B-84BA-65366B84E2D4}',CONVERT(datetime,'2019-07-09 11:51:21.607',121));

COMMIT TRANSACTION

