SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;9d5799

-- SQRIBE/TABLE;9d5799
-- Adding 2 rows to dbo.umbracoMediaVersion

BEGIN TRANSACTION

-- SQRIBE/INSERT;9d5799
INSERT INTO [dbo].[umbracoMediaVersion] ([id],[path]) VALUES (3,NULL);
-- SQRIBE/INSERT;9d5799
INSERT INTO [dbo].[umbracoMediaVersion] ([id],[path]) VALUES (4,N'/media/ozwf5in5/argentini-street-sign.png');

COMMIT TRANSACTION

