SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;03d113

-- SQRIBE/TABLE;03d113
-- Adding 1 row to dbo.UFRecordDataDateTime

SET IDENTITY_INSERT [dbo].[UFRecordDataDateTime] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[UFRecordDataDateTime] ([Id],[Key],[Value]) VALUES (1,'E2D46412-DC3C-4E88-8DF1-1364E3C56AC6',CONVERT(datetime,'2019-07-18 00:00:00.000',121));

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[UFRecordDataDateTime] OFF

