SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;9d5799

-- SQRIBE/TABLE;9d5799
-- Adding 2 rows to dbo.umbracoUser2UserGroup

BEGIN TRANSACTION

-- SQRIBE/INSERT;9d5799
INSERT INTO [dbo].[umbracoUser2UserGroup] ([userId],[userGroupId]) VALUES (-1,1);
-- SQRIBE/INSERT;9d5799
INSERT INTO [dbo].[umbracoUser2UserGroup] ([userId],[userGroupId]) VALUES (-1,5);

COMMIT TRANSACTION

