SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;ef17d2

-- SQRIBE/TABLE;ef17d2
-- Adding 2 rows to dbo.umbracoKeyValue

BEGIN TRANSACTION

-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[umbracoKeyValue] ([key],[value],[updated]) VALUES (N'Umbraco.Core.Upgrader.State+Umbraco.Core',N'{5B1E0D93-F5A3-449B-84BA-65366B84E2D4}',CONVERT(datetime,'2019-07-09 11:51:21.607',121));
-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[umbracoKeyValue] ([key],[value],[updated]) VALUES (N'Umbraco.Core.Upgrader.State+UmbracoForms',N'{forms-init-complete}',CONVERT(datetime,'2019-07-23 11:20:20.247',121));

COMMIT TRANSACTION

