SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;0caaa3

-- SQRIBE/TABLE;0caaa3
-- Adding 25 rows to dbo.cmsContentNu

BEGIN TRANSACTION

-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1056,0,N'{"properties":{"metaTitle":[{"culture":"","seg":"","val":"Bolide Homepage"}],"metaKeywords":[{"culture":"","seg":"","val":"carbide, bolide"}],"metaDescription":[{"culture":"","seg":"","val":"This is the Bolide home page."}],"shareImage":[{"culture":"","seg":"","val":"{\r\n  \"src\": \"/media/bgbjfdbt/argentini-street-sign.png\",\r\n  \"focalPoint\": {\r\n    \"left\": 0.5,\r\n    \"top\": 0.49855889927635211\r\n  },\r\n  \"crops\": [\r\n    {\r\n      \"alias\": \"SocialSharing\",\r\n      \"width\": 1200,\r\n      \"height\": 800,\r\n      \"coordinates\": {\r\n        \"x1\": 0.0753283912082195,\r\n        \"y1\": 1.894780628694E-16,\r\n        \"x2\": 0.077227207699310976,\r\n        \"y2\": 0\r\n      }\r\n    }\r\n  ]\r\n}"}],"pageContent":[{"culture":"","seg":"","val":"[{\"key\":\"ec19de18-a15e-4b83-a1c6-fdaa2e8a4c3e\",\"name\":\"Home Hero\",\"ncContentTypeAlias\":\"componentPicker\",\"contentName\":\"Home Hero\",\"contentComponents\":\"umb://document/5297d3fee9bd43e2be9d74b9aad38525\",\"enabled\":1},{\"key\":\"622d9311-31c9-461a-ba5a-ec16c94c4e68\",\"name\":\"Intro Paragraph\",\"ncContentTypeAlias\":\"bolideRichContent\",\"contentName\":\"Intro Paragraph\",\"enabled\":1,\"headline\":\"Welcome to Bolide!\",\"headlineStyle\":\"h1\",\"richContent\":\"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\",\"buttonSeparator\":null,\"buttonText\":\"Learn More\",\"buttonLink\":null,\"buttonURL\":\"https://fynydd.com\",\"buttonAlignment\":\"Center\"}]"}]},"cultureData":{},"urlSegment":"home-1"}',3);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1056,1,N'{"properties":{"metaTitle":[{"culture":"","seg":"","val":"Bolide Homepage"}],"metaKeywords":[{"culture":"","seg":"","val":"carbide, bolide"}],"metaDescription":[{"culture":"","seg":"","val":"This is the Bolide home page."}],"shareImage":[{"culture":"","seg":"","val":"{\r\n  \"src\": \"/media/bgbjfdbt/argentini-street-sign.png\",\r\n  \"focalPoint\": {\r\n    \"left\": 0.5,\r\n    \"top\": 0.49855889927635211\r\n  },\r\n  \"crops\": [\r\n    {\r\n      \"alias\": \"SocialSharing\",\r\n      \"width\": 1200,\r\n      \"height\": 800,\r\n      \"coordinates\": {\r\n        \"x1\": 0.0753283912082195,\r\n        \"y1\": 1.894780628694E-16,\r\n        \"x2\": 0.077227207699310976,\r\n        \"y2\": 0\r\n      }\r\n    }\r\n  ]\r\n}"}],"pageContent":[{"culture":"","seg":"","val":"[{\"key\":\"ec19de18-a15e-4b83-a1c6-fdaa2e8a4c3e\",\"name\":\"Home Hero\",\"ncContentTypeAlias\":\"componentPicker\",\"contentName\":\"Home Hero\",\"contentComponents\":\"umb://document/5297d3fee9bd43e2be9d74b9aad38525\",\"enabled\":1},{\"key\":\"622d9311-31c9-461a-ba5a-ec16c94c4e68\",\"name\":\"Intro Paragraph\",\"ncContentTypeAlias\":\"bolideRichContent\",\"contentName\":\"Intro Paragraph\",\"enabled\":1,\"headline\":\"Welcome to Bolide!\",\"headlineStyle\":\"h1\",\"richContent\":\"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\",\"buttonSeparator\":null,\"buttonText\":\"Learn More\",\"buttonLink\":null,\"buttonURL\":\"https://fynydd.com\",\"buttonAlignment\":\"Center\"}]"}]},"cultureData":{},"urlSegment":"home-1"}',3);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1057,0,N'{"properties":{},"cultureData":{},"urlSegment":"sample-images"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1058,0,N'{"properties":{"umbracoFile":[{"culture":"","seg":"","val":"{\"src\":\"/media/ozwf5in5/argentini-street-sign.png\",\"crops\":null}"}],"umbracoWidth":[{"culture":"","seg":"","val":2563}],"umbracoHeight":[{"culture":"","seg":"","val":1448}],"umbracoBytes":[{"culture":"","seg":"","val":"7098917"}],"umbracoExtension":[{"culture":"","seg":"","val":"png"}]},"cultureData":{},"urlSegment":"argentini-street-sign"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1071,0,N'{"properties":{"umbracoFile":[{"culture":"","seg":"","val":"{\"src\":\"/media/s3mlewii/03756_mountcooksunset_5120x2880.jpg\",\"crops\":[{\"alias\":\"SocialSharing\",\"width\":1200,\"height\":800}]}"}],"umbracoWidth":[{"culture":"","seg":"","val":5120}],"umbracoHeight":[{"culture":"","seg":"","val":2880}],"umbracoBytes":[{"culture":"","seg":"","val":"2808070"}],"umbracoExtension":[{"culture":"","seg":"","val":"jpg"}]},"cultureData":{},"urlSegment":"03756-mountcooksunset-5120x2880"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1072,0,N'{"properties":{"umbracoFile":[{"culture":"","seg":"","val":"{\"src\":\"/media/1eycjz0v/03560_thetopangagradient_5120x2880.jpg\",\"crops\":[{\"alias\":\"SocialSharing\",\"width\":1200,\"height\":800}]}"}],"umbracoWidth":[{"culture":"","seg":"","val":5120}],"umbracoHeight":[{"culture":"","seg":"","val":2880}],"umbracoBytes":[{"culture":"","seg":"","val":"3970980"}],"umbracoExtension":[{"culture":"","seg":"","val":"jpg"}]},"cultureData":{},"urlSegment":"03560-thetopangagradient-5120x2880"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1073,0,N'{"properties":{"umbracoFile":[{"culture":"","seg":"","val":"{\"src\":\"/media/qwqf44ny/03588_morrainelake_5120x2880.jpg\",\"crops\":[{\"alias\":\"SocialSharing\",\"width\":1200,\"height\":800}]}"}],"umbracoWidth":[{"culture":"","seg":"","val":5120}],"umbracoHeight":[{"culture":"","seg":"","val":2880}],"umbracoBytes":[{"culture":"","seg":"","val":"5101960"}],"umbracoExtension":[{"culture":"","seg":"","val":"jpg"}]},"cultureData":{},"urlSegment":"03588-morrainelake-5120x2880"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1078,0,N'{"properties":{},"cultureData":{},"urlSegment":"content-components"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1078,1,N'{"properties":{},"cultureData":{},"urlSegment":"content-components"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1080,0,N'{"properties":{},"cultureData":{},"urlSegment":"simple-heros"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1080,1,N'{"properties":{},"cultureData":{},"urlSegment":"simple-heros"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1081,0,N'{"properties":{"zeroCssProperties":[{"culture":"","seg":"","val":"--foreground-color: white;"}],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"frames":[{"culture":"","seg":"","val":"[{\"key\":\"9cd9ebfd-1c7e-4250-a875-0f599ba86b44\",\"name\":\"Item 1\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/95149a2b88ed462aa21ca1812e7fbde1\",\"title\":\"Bolide Site 1 Frame Title\",\"excerpt\":\"<p>This is a sample excerpt.</p>\",\"buttonText\":\"Bolide Site 2\",\"buttonLink\":\"umb://document/cdca7afe6c2443fdae456a6bdda0ace0\",\"buttonUrl\":null,\"enabled\":1},{\"key\":\"d2e05de0-d406-402d-befa-a8b216fdad14\",\"name\":\"Item 2\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/eb86bff880c04f58b45b565cf5229a76\",\"title\":\"Bolide Site 1 Frame Title 2\",\"excerpt\":\"<p>This is another sample excerpt.</p>\",\"buttonText\":\"Visit Apple\",\"buttonLink\":null,\"buttonUrl\":\"http://apple.com\",\"enabled\":1},{\"key\":\"5a50836d-2af6-42fc-98b4-ac9d06008f62\",\"name\":\"Item 3\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/3dd4230875924589a7042ee90b8a5a8e\",\"title\":\"Bolide Site 1 Frame Title 3\",\"excerpt\":\"<p>This is yet another frame excerpt.</p>\",\"buttonText\":\"Visit Google\",\"buttonLink\":null,\"buttonUrl\":\"http://google.com\",\"enabled\":1}]"}],"frameDuration":[{"culture":"","seg":"","val":7000}],"bgTransitionTime":[{"culture":"","seg":"","val":1000}],"showCountdown":[{"culture":"","seg":"","val":1}],"frameTransitionTime":[{"culture":"","seg":"","val":1500}],"cSSHelp":[]},"cultureData":{},"urlSegment":"home-hero"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1081,1,N'{"properties":{"zeroCssProperties":[{"culture":"","seg":"","val":"--foreground-color: white;"}],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"frames":[{"culture":"","seg":"","val":"[{\"key\":\"9cd9ebfd-1c7e-4250-a875-0f599ba86b44\",\"name\":\"Item 1\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/95149a2b88ed462aa21ca1812e7fbde1\",\"title\":\"Bolide Site 1 Frame Title\",\"excerpt\":\"<p>This is a sample excerpt.</p>\",\"buttonText\":\"Bolide Site 2\",\"buttonLink\":\"umb://document/cdca7afe6c2443fdae456a6bdda0ace0\",\"buttonUrl\":null,\"enabled\":1},{\"key\":\"d2e05de0-d406-402d-befa-a8b216fdad14\",\"name\":\"Item 2\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/eb86bff880c04f58b45b565cf5229a76\",\"title\":\"Bolide Site 1 Frame Title 2\",\"excerpt\":\"<p>This is another sample excerpt.</p>\",\"buttonText\":\"Visit Apple\",\"buttonLink\":null,\"buttonUrl\":\"http://apple.com\",\"enabled\":1},{\"key\":\"5a50836d-2af6-42fc-98b4-ac9d06008f62\",\"name\":\"Item 3\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/3dd4230875924589a7042ee90b8a5a8e\",\"title\":\"Bolide Site 1 Frame Title 3\",\"excerpt\":\"<p>This is yet another frame excerpt.</p>\",\"buttonText\":\"Visit Google\",\"buttonLink\":null,\"buttonUrl\":\"http://google.com\",\"enabled\":1}]"}],"frameDuration":[{"culture":"","seg":"","val":7000}],"bgTransitionTime":[{"culture":"","seg":"","val":1000}],"showCountdown":[{"culture":"","seg":"","val":1}],"frameTransitionTime":[{"culture":"","seg":"","val":1500}],"cSSHelp":[]},"cultureData":{},"urlSegment":"home-hero"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1085,0,N'{"properties":{"metaTitle":[{"culture":"","seg":"","val":"Home 2"}],"metaKeywords":[],"metaDescription":[{"culture":"","seg":"","val":"Second home page"}],"shareImage":[],"pageContent":[{"culture":"","seg":"","val":"[{\"key\":\"4a007158-2856-453c-9aa0-644921def365\",\"name\":\"Item 1\",\"ncContentTypeAlias\":\"componentPicker\",\"contentName\":\"Site 2 Home Hero\",\"contentComponents\":\"umb://document/61904f3df21e4d73a6539cc16eaf4d04\"}]"}]},"cultureData":{},"urlSegment":"home-2"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1085,1,N'{"properties":{"metaTitle":[{"culture":"","seg":"","val":"Home 2"}],"metaKeywords":[],"metaDescription":[{"culture":"","seg":"","val":"Second home page"}],"shareImage":[],"pageContent":[{"culture":"","seg":"","val":"[{\"key\":\"4a007158-2856-453c-9aa0-644921def365\",\"name\":\"Item 1\",\"ncContentTypeAlias\":\"componentPicker\",\"contentName\":\"Site 2 Home Hero\",\"contentComponents\":\"umb://document/61904f3df21e4d73a6539cc16eaf4d04\"}]"}]},"cultureData":{},"urlSegment":"home-2"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1086,0,N'{"properties":{},"cultureData":{},"urlSegment":"content-components"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1086,1,N'{"properties":{},"cultureData":{},"urlSegment":"content-components"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1087,0,N'{"properties":{},"cultureData":{},"urlSegment":"simple-heros"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1087,1,N'{"properties":{},"cultureData":{},"urlSegment":"simple-heros"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1088,0,N'{"properties":{"zeroCssProperties":[],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"frames":[{"culture":"","seg":"","val":"[{\"key\":\"b01667c6-57ae-4264-a763-644fce0fb4cc\",\"name\":\"Item 1\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/95149a2b88ed462aa21ca1812e7fbde1\",\"title\":\"Bolide Site 2 Frame Title\",\"excerpt\":\"<p>This is site 2 excerpt.</p>\",\"buttonText\":\"Visit Site 1\",\"buttonLink\":\"umb://document/7a4e2b57a6cd4f7f92655069de668479\",\"buttonUrl\":null,\"enabled\":1}]"}],"frameDuration":[{"culture":"","seg":"","val":5000}],"bgTransitionTime":[{"culture":"","seg":"","val":1000}],"showCountdown":[{"culture":"","seg":"","val":1}],"frameTransitionTime":[{"culture":"","seg":"","val":1500}],"cSSHelp":[]},"cultureData":{},"urlSegment":"site-2-hero"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1088,1,N'{"properties":{"zeroCssProperties":[],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"frames":[{"culture":"","seg":"","val":"[{\"key\":\"b01667c6-57ae-4264-a763-644fce0fb4cc\",\"name\":\"Item 1\",\"ncContentTypeAlias\":\"bolideSimpleHeroFrame\",\"backgroundImage\":\"umb://media/95149a2b88ed462aa21ca1812e7fbde1\",\"title\":\"Bolide Site 2 Frame Title\",\"excerpt\":\"<p>This is site 2 excerpt.</p>\",\"buttonText\":\"Visit Site 1\",\"buttonLink\":\"umb://document/7a4e2b57a6cd4f7f92655069de668479\",\"buttonUrl\":null,\"enabled\":1}]"}],"frameDuration":[{"culture":"","seg":"","val":5000}],"bgTransitionTime":[{"culture":"","seg":"","val":1000}],"showCountdown":[{"culture":"","seg":"","val":1}],"frameTransitionTime":[{"culture":"","seg":"","val":1500}],"cSSHelp":[]},"cultureData":{},"urlSegment":"site-2-hero"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1094,0,N'{"properties":{"zeroCssProperties":[{"culture":"","seg":"","val":"--background-color: var(--sf-color-white);\n--foreground-color: var(--sf-color-white-contrast);"}],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"companyName":[{"culture":"","seg":"","val":"Bolide Site 1"}],"streetAddress":[],"streetAddressLine2":[],"city":[],"stateOrProvince":[],"postalCode":[],"country":[],"mainTelephone":[],"facebookURL":[],"twitterURL":[],"youTubeURL":[],"linkedInURL":[],"pinterestURL":[],"customCssHelp":[],"customFontURLs":[{"culture":"","seg":"","val":"@import url(''https://fonts.googleapis.com/css?family=Merriweather&display=swap'');"}],"bodyFontStack":[{"culture":"","seg":"","val":"Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Calibri, Arial, sans-serif"}],"monoFontStack":[{"culture":"","seg":"","val":"\"Source Code Pro\", -apple-system-mono, Menlo, Consolas, Monaco, \"Andale Mono\", \"Lucida Console\", \"Lucida Sans Typewriter\", Courier, \"Courier New\", monospace"}],"headlineFontStack":[{"culture":"","seg":"","val":"Merriweather, var(--font-body)"}]},"cultureData":{},"urlSegment":"settings"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1094,1,N'{"properties":{"zeroCssProperties":[{"culture":"","seg":"","val":"--background-color: var(--sf-color-white);\n--foreground-color: var(--sf-color-white-contrast);"}],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"companyName":[{"culture":"","seg":"","val":"Bolide Site 1"}],"streetAddress":[],"streetAddressLine2":[],"city":[],"stateOrProvince":[],"postalCode":[],"country":[],"mainTelephone":[],"facebookURL":[],"twitterURL":[],"youTubeURL":[],"linkedInURL":[],"pinterestURL":[],"customCssHelp":[],"customFontURLs":[{"culture":"","seg":"","val":"@import url(''https://fonts.googleapis.com/css?family=Merriweather&display=swap'');"}],"bodyFontStack":[{"culture":"","seg":"","val":"Roboto, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Calibri, Arial, sans-serif"}],"monoFontStack":[{"culture":"","seg":"","val":"\"Source Code Pro\", -apple-system-mono, Menlo, Consolas, Monaco, \"Andale Mono\", \"Lucida Console\", \"Lucida Sans Typewriter\", Courier, \"Courier New\", monospace"}],"headlineFontStack":[{"culture":"","seg":"","val":"Merriweather, var(--font-body)"}]},"cultureData":{},"urlSegment":"settings"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1095,0,N'{"properties":{"zeroCssProperties":[],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"companyName":[{"culture":"","seg":"","val":"Bolide Site 2"}],"streetAddress":[],"streetAddressLine2":[],"city":[],"stateOrProvince":[],"postalCode":[],"country":[],"mainTelephone":[],"facebookURL":[],"twitterURL":[],"youTubeURL":[],"linkedInURL":[],"pinterestURL":[],"customCssHelp":[],"customFontURLs":[],"bodyFontStack":[],"monoFontStack":[],"headlineFontStack":[]},"cultureData":{},"urlSegment":"settings"}',0);
-- SQRIBE/INSERT;0caaa3
INSERT INTO [dbo].[cmsContentNu] ([nodeId],[published],[data],[rv]) VALUES (1095,1,N'{"properties":{"zeroCssProperties":[],"phabCssProperties":[],"tabpCssProperties":[],"tablCssProperties":[],"noteCssProperties":[],"deskCssProperties":[],"elasCssProperties":[],"introText":[],"companyName":[{"culture":"","seg":"","val":"Bolide Site 2"}],"streetAddress":[],"streetAddressLine2":[],"city":[],"stateOrProvince":[],"postalCode":[],"country":[],"mainTelephone":[],"facebookURL":[],"twitterURL":[],"youTubeURL":[],"linkedInURL":[],"pinterestURL":[],"customCssHelp":[],"customFontURLs":[],"bodyFontStack":[],"monoFontStack":[],"headlineFontStack":[]},"cultureData":{},"urlSegment":"settings"}',0);

COMMIT TRANSACTION

