SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;820494

-- SQRIBE/TABLE;820494
-- Adding 3 rows to dbo.umbracoUser2UserGroup

BEGIN TRANSACTION

-- SQRIBE/INSERT;820494
INSERT INTO [dbo].[umbracoUser2UserGroup] ([userId],[userGroupId]) VALUES (-1,1);
-- SQRIBE/INSERT;820494
INSERT INTO [dbo].[umbracoUser2UserGroup] ([userId],[userGroupId]) VALUES (-1,5);
-- SQRIBE/INSERT;820494
INSERT INTO [dbo].[umbracoUser2UserGroup] ([userId],[userGroupId]) VALUES (1,3);

COMMIT TRANSACTION

