SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;03d113

-- SQRIBE/TABLE;03d113
-- Adding 1 row to dbo.UFRecordDataBit

SET IDENTITY_INSERT [dbo].[UFRecordDataBit] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;03d113
INSERT INTO [dbo].[UFRecordDataBit] ([Id],[Key],[Value]) VALUES (1,'B82C187A-077C-4890-B3A0-B61AACAFEA6D',1);

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[UFRecordDataBit] OFF

