SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;ef17d2

-- SQRIBE/TABLE;ef17d2
-- Adding 4 rows to dbo.UFUserFormSecurity

SET IDENTITY_INSERT [dbo].[UFUserFormSecurity] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[UFUserFormSecurity] ([Id],[User],[Form],[HasAccess],[AllowInEditor],[SecurityType]) VALUES (3,N'-1','DEB50D01-FF86-4CEE-920B-9F8F9C637CF8',1,1,0);
-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[UFUserFormSecurity] ([Id],[User],[Form],[HasAccess],[AllowInEditor],[SecurityType]) VALUES (2,N'1','DEB50D01-FF86-4CEE-920B-9F8F9C637CF8',1,1,0);
-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[UFUserFormSecurity] ([Id],[User],[Form],[HasAccess],[AllowInEditor],[SecurityType]) VALUES (8,N'-1','2D4C06FD-7D7A-4E8B-B7F9-0412CBC7D945',1,1,0);
-- SQRIBE/INSERT;ef17d2
INSERT INTO [dbo].[UFUserFormSecurity] ([Id],[User],[Form],[HasAccess],[AllowInEditor],[SecurityType]) VALUES (9,N'1','2D4C06FD-7D7A-4E8B-B7F9-0412CBC7D945',0,0,0);

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[UFUserFormSecurity] OFF

