SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;528484

-- SQRIBE/TABLE;528484
-- Adding 1 row to dbo.umbracoMediaVersion

BEGIN TRANSACTION

-- SQRIBE/INSERT;528484
INSERT INTO [dbo].[umbracoMediaVersion] ([id],[path]) VALUES (41153,NULL);

COMMIT TRANSACTION

